version: '3.8'
services:
  Cochonade:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    networks:
      - COCHON
  Cochonade-db:
    image: mysql:8
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD:  ${ROOT_PASSWORD}
    networks:
      - COCHON
networks:
  COCHON:
    external: true
